# Employee Attrition Prediction

## Phase 2: Data Preprocessing

### Objective

The objective of this notebook is to prepare the employee attrition dataset for machine learning.

This notebook includes:

- Importing required libraries
- Loading the dataset
- Creating a working copy
- Handling missing values
- Removing unnecessary features
- Encoding categorical variables
- Feature scaling
- Saving the processed dataset

In [310]:
# Import required libraries

import pandas as pd
import numpy as np
import joblib

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

## Load Dataset

Load the Employee Attrition dataset into a pandas DataFrame.

In [311]:
# Load dataset

df = pd.read_csv("../Dataset/WA_Fn-UseC_-HR-Employee-Attrition.csv")

# Display first five rows

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

## Create a Working Copy

A separate copy of the dataset is created so that preprocessing operations do not modify the original data.

In [312]:
# Create a copy of the dataset

data = df.copy()

# Display shape

data.shape

(1470, 35)

## Check Missing Values

Verify whether the dataset contains any missing values before applying preprocessing techniques.

In [313]:
# Missing values

data.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

#### Interpretation

No missing values are present in the dataset.

Therefore, no imputation techniques are required.

## Check Duplicate Records

Verify whether the dataset contains duplicate records before applying preprocessing techniques.

In [314]:
# Check duplicate rows

duplicate_rows = data.duplicated().sum()

print(f"Total Duplicate Records: {duplicate_rows}")

Total Duplicate Records: 0

#### Interpretation

No duplicate records were found in the dataset.

Therefore, duplicate removal is not required.

## Identify Constant Columns

Columns containing only one unique value do not provide useful information for machine learning models.

Such columns are identified before removal.

In [315]:
# Identify constant columns

constant_columns = [
    column
    for column in data.columns
    if data[column].nunique() == 1
]

print("Constant Columns:")
print(constant_columns)

Constant Columns:
['EmployeeCount', 'Over18', 'StandardHours']

#### Interpretation

Three columns contain only a single unique value throughout the dataset.

Since these features do not contribute any predictive information, they will be removed.

## Remove Unnecessary Features

Remove identifier columns and constant columns that do not contribute to employee attrition prediction.

In [316]:
# Drop unnecessary columns

columns_to_drop = constant_columns + ["EmployeeNumber"]

data.drop(columns=columns_to_drop, inplace=True)

print(f"Dataset Shape after Preprocessing: {data.shape}")

Dataset Shape after Preprocessing: (1470, 31)

In [317]:
data.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,3,4,1,6,3,3,2,2,2,2

#### Interpretation

Identifier and constant columns have been removed successfully.

The remaining features contain useful information for predictive modeling.

# Handle Categorical Variables

Machine learning algorithms cannot directly process text values.

Therefore, all categorical features are converted into numerical representations using Label Encoding.

This ensures that the dataset is suitable for model training.

### Encode Categorical Features

In [318]:
# Import LabelEncoder

from sklearn.preprocessing import LabelEncoder

# Create a copy of the dataset

data = df.copy()

# Store all encoders

encoders = {}

# Find categorical columns

cat_cols = data.select_dtypes(include="object").columns

# Encode categorical columns

for col in cat_cols:

    le = LabelEncoder()

    data[col] = le.fit_transform(data[col])

    encoders[col] = le

print("Categorical features encoded successfully.")

Categorical features encoded successfully.

C:\Users\jains\AppData\Local\Temp\ipykernel_29080\1774961217.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = data.select_dtypes(include="object").columns

In [319]:
processed_data = data.copy()

### Save lable Encoders

All label encoders are saved so the Streamlit application can transform user inputs using exactly the same mappings used during training.

In [320]:
# Save all encoders

joblib.dump(encoders, "../Model/encoders.pkl")

print("Encoders saved successfully.")

Encoders saved successfully.

In [321]:
processed_data.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,2,1102,2,1,2,1,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,0,1,279,1,8,1,1,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,1,2,1373,1,2,2,4,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,0,1,1392,1,3,4,1,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,0,2,591,1,2,1,3,1,7,...,4,80,1,6,3,3,2,2,2,2

#### Interpretation

All categorical variables have been successfully converted into numerical values.

The dataset is now compatible with machine learning algorithms that require numerical input.

## Verify Encoded Dataset

Display the first five records of the encoded dataset to confirm that all categorical variables have been successfully converted into numerical values.

In [322]:
# Display the encoded dataset

processed_data.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,2,1102,2,1,2,1,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,0,1,279,1,8,1,1,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,1,2,1373,1,2,2,4,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,0,1,1392,1,3,4,1,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,0,2,591,1,2,1,3,1,7,...,4,80,1,6,3,3,2,2,2,2

## Verify Data Types

Verify that all features are now represented using numerical data types.

In [323]:
# Display data types

processed_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   int64
 2   BusinessTravel            1470 non-null   int64
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   int64
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   int64
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   int64
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   int64
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   int64
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   int64
 22  OverTime                  1470 non-null   int64
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(35)
memory usage: 402.1 KB

# Feature Scaling

The numerical features in the dataset have different value ranges.

Feature scaling standardizes these values so that each feature contributes equally during model training, improving the performance of many machine learning algorithms.

In [324]:
processed_data.dtypes

Age                         int64
Attrition                   int64
BusinessTravel              int64
DailyRate                   int64
Department                  int64
DistanceFromHome            int64
Education                   int64
EducationField              int64
EmployeeCount               int64
EmployeeNumber              int64
EnvironmentSatisfaction     int64
Gender                      int64
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobRole                     int64
JobSatisfaction             int64
MaritalStatus               int64
MonthlyIncome               int64
MonthlyRate                 int64
NumCompaniesWorked          int64
Over18                      int64
OverTime                    int64
PercentSalaryHike           int64
PerformanceRating           int64
RelationshipSatisfaction    int64
StandardHours               int64
StockOptionLevel            int64
TotalWorkingYears           int64
TrainingTimesLastYear       int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsSinceLastPromotion     int64
YearsWithCurrManager        int64
dtype: object

In [325]:
# Import StandardScaler

from sklearn.preprocessing import StandardScaler

## Separate Features and Target Variable

Separate the independent features (X) from the target variable (y) before applying feature scaling.

In [326]:
# Separate features and target

X = processed_data.drop("Attrition", axis=1)
y = processed_data["Attrition"]

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (1470, 34)
Target Shape: (1470,)

## Apply Feature Scaling

Standardize the feature values using StandardScaler.

Only the independent features are scaled, while the target variable remains unchanged.

In [327]:
print(X.select_dtypes(include="object").columns)

Index([], dtype='str')

In [328]:
print(processed_data.head())

   Age  Attrition  BusinessTravel  DailyRate  Department  DistanceFromHome  \
0   41          1               2       1102           2                 1
1   49          0               1        279           1                 8
2   37          1               2       1373           1                 2
3   33          0               1       1392           1                 3
4   27          0               2        591           1                 2

   Education  EducationField  EmployeeCount  EmployeeNumber  ...  \
0          2               1              1               1  ...
1          1               1              1               2  ...
2          2               4              1               4  ...
3          4               1              1               5  ...
4          1               3              1               7  ...

   RelationshipSatisfaction  StandardHours  StockOptionLevel  \
0                         1             80                 0
1                         4             80                 1
2                         2             80                 0
3                         3             80                 0
4                         4             80                 1

   TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
0                  8                      0                1               6
1                 10                      3                3              10
2                  7                      3                3               0
3                  8                      3                3               8
4                  6                      3                3               2

   YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager
0                   4                        0                     5
1                   7                        1                     7
2                   0                        0                     0
3                   7                        3                     0
4                   2                        2                     2

[5 rows x 35 columns]

In [329]:
print(processed_data.dtypes)

Age                         int64
Attrition                   int64
BusinessTravel              int64
DailyRate                   int64
Department                  int64
DistanceFromHome            int64
Education                   int64
EducationField              int64
EmployeeCount               int64
EmployeeNumber              int64
EnvironmentSatisfaction     int64
Gender                      int64
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobRole                     int64
JobSatisfaction             int64
MaritalStatus               int64
MonthlyIncome               int64
MonthlyRate                 int64
NumCompaniesWorked          int64
Over18                      int64
OverTime                    int64
PercentSalaryHike           int64
PerformanceRating           int64
RelationshipSatisfaction    int64
StandardHours               int64
StockOptionLevel            int64
TotalWorkingYears           int64
TrainingTimesLastYear       int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsSinceLastPromotion     int64
YearsWithCurrManager        int64
dtype: object

In [330]:
# Initialize StandardScaler

scaler = StandardScaler()

# Scale the features

X_scaled = scaler.fit_transform(X)

X_scaled = pd.DataFrame(
    X_scaled,
    columns=X.columns
)

###Save Feature Scaler

The trained scaler is saved to ensure that user inputs are standardized in the same way as the training dataset.

In [331]:
# Save scaler

joblib.dump(scaler, "../Model/scaler.pkl")

print("Scaler saved successfully.")

Scaler saved successfully.

### Save Feature Order

The feature order is saved so that the Streamlit application passes the input variables to the trained model in the exact sequence expected.

In [332]:
# Save feature order

joblib.dump(X.columns.tolist(), "../Model/features.pkl")

print("Feature order saved successfully.")

Feature order saved successfully.

In [333]:
# Convert scaled data back into a DataFrame

X_scaled = pd.DataFrame(
    X_scaled,
    columns=X.columns
)

X_scaled.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,0.446350,0.590048,0.742527,1.401512,-1.010909,-0.891688,-0.937414,0.0,-1.701283,-0.660531,...,-1.584178,0.0,-0.932014,-0.421642,-2.171982,-2.493820,-0.164613,-0.063296,-0.679146,0.245834
1,1.322365,-0.913194,-1.297775,-0.493817,-0.147150,-1.868426,-0.937414,0.0,-1.699621,0.254625,...,1.191438,0.0,0.241988,-0.164511,0.155707,0.338096,0.488508,0.764998,-0.368715,0.806541
2,0.008343,0.590048,1.414363,-0.493817,-0.887515,-0.891688,1.316673,0.0,-1.696298,1.169781,...,-0.658973,0.0,-0.932014,-0.550208,0.155707,0.338096,-1.144294,-1.167687,-0.679146,-1.155935
3,-0.429664,-0.913194,1.461466,-0.493817,-0.764121,1.061787,-0.937414,0.0,-1.694636,1.169781,...,0.266233,0.0,-0.932014,-0.421642,0.155707,0.338096,0.161947,0.764998,0.252146,-1.155935
4,-1.086676,0.590048,-0.524295,-0.493817,-0.887515,-1.868426,0.565311,0.0,-1.691313,-1.575686,...,1.191438,0.0,0.241988,-0.678774,0.155707,0.338096,-0.817734,-0.615492,-0.058285,-0.595227

#### Interpretation

The independent features have been standardized using StandardScaler.

Each feature now has a mean close to 0 and a standard deviation close to 1, ensuring that variables with larger numerical ranges do not dominate the learning process.

The target variable was intentionally excluded from scaling because it represents the class labels for prediction.

# Save Processed Dataset

The preprocessed dataset is saved as a new CSV file.

This allows the cleaned and transformed data to be reused in later stages of the project without repeating preprocessing.

In [334]:
processed_data = X_scaled.copy()

processed_data["Attrition"] = y

In [335]:
# Combine scaled features and target variable

processed_dataset = X_scaled.copy()

processed_dataset["Attrition"] = y.values

# Display first five rows

processed_dataset.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition
0,0.446350,0.590048,0.742527,1.401512,-1.010909,-0.891688,-0.937414,0.0,-1.701283,-0.660531,...,0.0,-0.932014,-0.421642,-2.171982,-2.493820,-0.164613,-0.063296,-0.679146,0.245834,1
1,1.322365,-0.913194,-1.297775,-0.493817,-0.147150,-1.868426,-0.937414,0.0,-1.699621,0.254625,...,0.0,0.241988,-0.164511,0.155707,0.338096,0.488508,0.764998,-0.368715,0.806541,0
2,0.008343,0.590048,1.414363,-0.493817,-0.887515,-0.891688,1.316673,0.0,-1.696298,1.169781,...,0.0,-0.932014,-0.550208,0.155707,0.338096,-1.144294,-1.167687,-0.679146,-1.155935,1
3,-0.429664,-0.913194,1.461466,-0.493817,-0.764121,1.061787,-0.937414,0.0,-1.694636,1.169781,...,0.0,-0.932014,-0.421642,0.155707,0.338096,0.161947,0.764998,0.252146,-1.155935,0
4,-1.086676,0.590048,-0.524295,-0.493817,-0.887515,-1.868426,0.565311,0.0,-1.691313,-1.575686,...,0.0,0.241988,-0.678774,0.155707,0.338096,-0.817734,-0.615492,-0.058285,-0.595227,0

In [336]:
# Save processed dataset

processed_data.to_csv(
    "../Dataset/Processed_Employee_Attrition.csv",
    index=False
)
print("Processed dataset saved successfully.")

Processed dataset saved successfully.

## Verify Saved Dataset

Reload the saved dataset to ensure it has been stored correctly.

In [337]:
# Reload the processed dataset

verification_df = pd.read_csv("../Dataset/Processed_Employee_Attrition.csv")

verification_df.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition
0,0.446350,0.590048,0.742527,1.401512,-1.010909,-0.891688,-0.937414,0.0,-1.701283,-0.660531,...,0.0,-0.932014,-0.421642,-2.171982,-2.493820,-0.164613,-0.063296,-0.679146,0.245834,1
1,1.322365,-0.913194,-1.297775,-0.493817,-0.147150,-1.868426,-0.937414,0.0,-1.699621,0.254625,...,0.0,0.241988,-0.164511,0.155707,0.338096,0.488508,0.764998,-0.368715,0.806541,0
2,0.008343,0.590048,1.414363,-0.493817,-0.887515,-0.891688,1.316673,0.0,-1.696298,1.169781,...,0.0,-0.932014,-0.550208,0.155707,0.338096,-1.144294,-1.167687,-0.679146,-1.155935,1
3,-0.429664,-0.913194,1.461466,-0.493817,-0.764121,1.061787,-0.937414,0.0,-1.694636,1.169781,...,0.0,-0.932014,-0.421642,0.155707,0.338096,0.161947,0.764998,0.252146,-1.155935,0
4,-1.086676,0.590048,-0.524295,-0.493817,-0.887515,-1.868426,0.565311,0.0,-1.691313,-1.575686,...,0.0,0.241988,-0.678774,0.155707,0.338096,-0.817734,-0.615492,-0.058285,-0.595227,0

# Conclusion

The employee attrition dataset has been successfully preprocessed and prepared for machine learning.

The preprocessing steps completed in this notebook include:

- Verified data quality (missing values and duplicates)
- Removed unnecessary and constant features
- Encoded categorical variables into numerical format
- Standardized the feature values using StandardScaler
- Saved the processed dataset for future use

The dataset is now ready for feature engineering and model development.